/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_FFmpeg */

#ifndef _Included_com_jni_FFmpeg
#define _Included_com_jni_FFmpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_FFmpeg
 * Method:    run
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_FFmpeg_run
  (JNIEnv *, jclass);

/*
 * Class:     com_jni_FFmpeg
 * Method:    runCmd
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_FFmpeg_runCmd
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
