/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniTest_FFmpegCmd */

#ifndef _Included_FFmpeg_Cmd
#define _Included_FFmpeg_Cmd
#ifdef __cplusplus
extern "C" {
#endif

//JNIEXPORT jint JNICALL Java_Jni_FFmpegCmd_exec(JNIEnv *, jclass, jint, jobjectArray);
//
//JNIEXPORT void JNICALL Java_Jni_FFmpegCmd_exit(JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_jni_FFmpeg_run(JNIEnv *, jclass);

JNIEXPORT jint JNICALL Java_com_jni_FFmpeg_runCmd(JNIEnv *, jclass,jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif

void ffmpeg_progress(float progress);